### ISSUE TITLE
underpriced transaction errors

### ISSUE THREAD

**Issue by wighawag** [INFURA/infura#32]
on ropsten infura nodes are rejecting transaction with gas price as high as 21 gwei

There are multiple users reporting the same issue : https://github.com/ethereum/go-ethereum/issues/14838

For my dapp running on ropsten I would like to mimic the gasPrice I plan to use on the mainnet (as low as 1 gwei) but currently infura nodes is rejecting such transaction with the error "undepriced transaction"

it would be nice if infura node gasPrice limit where lower on ropsten. Actually they should match the statistics here : http://ethgasstation.info/ to represent better the real situation on the mainnet

**Comment by themandalore** [comment]
I think they fixed it...not getting the error now

**Comment by illya13** [comment]
still have it now

**Comment by wighawag** [comment]
even at 22 gwei tx get refused.

**Comment by illya13** [comment]
any update, still having this issue

**Comment by themandalore** [comment]
I've just been catching the error and then restarting it and it will work after a few times.  I think it may be infura charging more for multiple fast calls, but that's just a theory...but yeah I'm still getting it

**Comment by egalano** [comment]
To close this out, this ended up being a bug in geth 1.6.7 and was resolved after upgrading to geth>=1.7.0 https://github.com/ethereum/go-ethereum/issues/14838

**Comment by AVVS** [comment]
still happening with gas prices set to 1 gwei based on safe low of eth gas station

```
{"name":"capp-payments","hostname":"ms-mailer-production-0","pid":17,"level":30,"msg":"Gas price: 1 gwei","time":"2017-12-24T07:28:50.487Z","v":0}

{"name":"capp-payments","hostname":"ms-mailer-production-0","pid":17,"level":40,"msg":"Failed to create contract { code: -32000, message: 'transaction underpriced' }","time":"2017-12-24T07:28:51.369Z","v":0}
```

**Comment by daniel-van-niekerk** [comment]
Is there a fix for this? The standard gas price is SUPER expensive. 137 Gwei today? I want to manually set this to 22 of something reasonable but Infura rejects it for being to low.

**Comment by PaulRBerg** [comment]
Gas 60,000 and price 1 finney, it still didn't work. Opened an issue here: https://github.com/ethereum/web3.js/issues/1656

And full log output [here](https://www.dropbox.com/s/yydng4hhxnfdhjr/ethrereumjs-tx-0.0.5.log?dl=0).
